WORKSHOP_NAME=lab-ocp4-vsphere
WORKSHOP_IMAGE=image-registry.openshift-image-registry.svc:5000/ocp4-vsphere-workshop/lab-ocp4-vsphere:latest
WORKSHOP_TITLE="OpenShift 4.2 on vSphere"
WORKSHOP_DESCRIPTION="Deploying OpenShift 4.2 on vSphere"
WORKSHOP_FILE="ocp4-vsphere-workshop.yml"
CONSOLE_IMAGE=quay.io/openshift/origin-console:4.2
RESOURCE_BUDGET=x-large
MAX_SESSION_AGE=7200
IDLE_TIMEOUT=300
SPAWNER_MODE=hosted-workshop
OPENSHIFT_PROJECT="{username}"
